title: Designing Consensus
description: Gamified Modeling and Simulation of Collaborative Decision-Making
theme: just-the-docs

url: https://srcJin.github.io/DesigningConsensus

# aux_links:
#   Template Repository: https://github.com/just-the-docs/just-the-docs-template
